name: Nepse Data Auto Scrape

on:
  push:
    branches:
      - main
  schedule:
    - cron: '15 11 * * *' # 11:15am UTC => 05:00pm Nepal Time

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Execute Scraping Script
        run: |
          python scrape_nepse.py

      - name: Commit and push new data
        run: |
          git config --local user.email "jamesowis5@gmail.com"
          git config --local user.name "bhupennn"
          git add .
          git commit -am "Today's share data has been scrapped successfully!"
          
          # Use GitHub token for authentication
          git push https://github-actions:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git
